//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Org.Visiontech.Optometry
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap.service.optoplus.visiontech.org/", ConfigurationName="Org.Visiontech.Optometry.OptometrySoap")]
    public interface OptometrySoap
    {
        
        // CODEGEN: Il parametro 'arg0' richiede informazioni sullo schema aggiuntive che non possono essere acquisite utilizzando la modalità parametro. L'attributo specifico è 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(jsonbPolimorphic))]
        Org.Visiontech.Optometry.deleteResponse delete(Org.Visiontech.Optometry.delete request);
        
        // CODEGEN: Il parametro 'return' richiede informazioni sullo schema aggiuntive che non possono essere acquisite utilizzando la modalità parametro. L'attributo specifico è 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(jsonbPolimorphic))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Org.Visiontech.Optometry.editResponse edit(Org.Visiontech.Optometry.edit request);
        
        // CODEGEN: Il parametro 'return' richiede informazioni sullo schema aggiuntive che non possono essere acquisite utilizzando la modalità parametro. L'attributo specifico è 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(jsonbPolimorphic))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Org.Visiontech.Optometry.findResponse find(Org.Visiontech.Optometry.find request);
        
        // CODEGEN: Il parametro 'return' richiede informazioni sullo schema aggiuntive che non possono essere acquisite utilizzando la modalità parametro. L'attributo specifico è 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(jsonbPolimorphic))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Org.Visiontech.Optometry.createResponse create(Org.Visiontech.Optometry.create request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class optometryDTO : validableDTO
    {
        
        private opticalCorrectionsDTO correctionField;
        
        private bool currentField;
        
        private bool currentFieldSpecified;
        
        private forieDTO farForieField;
        
        private optometryParametersDTO farParametersField;
        
        private visusDTO farVisusField;
        
        private optometryParametersDTO intermediateParametersField;
        
        private keratometryDTO keratometryField;
        
        private System.DateTime measuredField;
        
        private bool measuredFieldSpecified;
        
        private forieDTO nearForieField;
        
        private optometryParametersDTO nearParametersField;
        
        private visusDTO nearVisusField;
        
        private string noteField;
        
        private personDTO oculistField;
        
        private personDTO patientField;
        
        private System.DateTime recallField;
        
        private bool recallFieldSpecified;
        
        private refractometryDTO refractometryField;
        
        private shopDTO shopField;
        
        private systemType typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public opticalCorrectionsDTO correction
        {
            get
            {
                return this.correctionField;
            }
            set
            {
                this.correctionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool current
        {
            get
            {
                return this.currentField;
            }
            set
            {
                this.currentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currentSpecified
        {
            get
            {
                return this.currentFieldSpecified;
            }
            set
            {
                this.currentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public forieDTO farForie
        {
            get
            {
                return this.farForieField;
            }
            set
            {
                this.farForieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public optometryParametersDTO farParameters
        {
            get
            {
                return this.farParametersField;
            }
            set
            {
                this.farParametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public visusDTO farVisus
        {
            get
            {
                return this.farVisusField;
            }
            set
            {
                this.farVisusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public optometryParametersDTO intermediateParameters
        {
            get
            {
                return this.intermediateParametersField;
            }
            set
            {
                this.intermediateParametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public keratometryDTO keratometry
        {
            get
            {
                return this.keratometryField;
            }
            set
            {
                this.keratometryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime measured
        {
            get
            {
                return this.measuredField;
            }
            set
            {
                this.measuredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool measuredSpecified
        {
            get
            {
                return this.measuredFieldSpecified;
            }
            set
            {
                this.measuredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public forieDTO nearForie
        {
            get
            {
                return this.nearForieField;
            }
            set
            {
                this.nearForieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public optometryParametersDTO nearParameters
        {
            get
            {
                return this.nearParametersField;
            }
            set
            {
                this.nearParametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public visusDTO nearVisus
        {
            get
            {
                return this.nearVisusField;
            }
            set
            {
                this.nearVisusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public personDTO oculist
        {
            get
            {
                return this.oculistField;
            }
            set
            {
                this.oculistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public personDTO patient
        {
            get
            {
                return this.patientField;
            }
            set
            {
                this.patientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public System.DateTime recall
        {
            get
            {
                return this.recallField;
            }
            set
            {
                this.recallField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool recallSpecified
        {
            get
            {
                return this.recallFieldSpecified;
            }
            set
            {
                this.recallFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public refractometryDTO refractometry
        {
            get
            {
                return this.refractometryField;
            }
            set
            {
                this.refractometryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public shopDTO shop
        {
            get
            {
                return this.shopField;
            }
            set
            {
                this.shopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public systemType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class opticalCorrectionsDTO : validableDTO
    {
        
        private opticalCorrectionDTO leftField;
        
        private opticalCorrectionDTO rightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public opticalCorrectionDTO left
        {
            get
            {
                return this.leftField;
            }
            set
            {
                this.leftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public opticalCorrectionDTO right
        {
            get
            {
                return this.rightField;
            }
            set
            {
                this.rightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(lensCorrectionDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class opticalCorrectionDTO : opticalParametersDTO
    {
        
        private double additionField;
        
        private bool additionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double addition
        {
            get
            {
                return this.additionField;
            }
            set
            {
                this.additionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool additionSpecified
        {
            get
            {
                return this.additionFieldSpecified;
            }
            set
            {
                this.additionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(opticalCorrectionDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(lensCorrectionDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(eyeParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(lensParametersDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class opticalParametersDTO : validableDTO
    {
        
        private double axisField;
        
        private bool axisFieldSpecified;
        
        private double cylinderField;
        
        private bool cylinderFieldSpecified;
        
        private double prismField;
        
        private bool prismFieldSpecified;
        
        private double prismAxisField;
        
        private bool prismAxisFieldSpecified;
        
        private double sphereField;
        
        private bool sphereFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double axis
        {
            get
            {
                return this.axisField;
            }
            set
            {
                this.axisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool axisSpecified
        {
            get
            {
                return this.axisFieldSpecified;
            }
            set
            {
                this.axisFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double cylinder
        {
            get
            {
                return this.cylinderField;
            }
            set
            {
                this.cylinderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cylinderSpecified
        {
            get
            {
                return this.cylinderFieldSpecified;
            }
            set
            {
                this.cylinderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double prism
        {
            get
            {
                return this.prismField;
            }
            set
            {
                this.prismField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prismSpecified
        {
            get
            {
                return this.prismFieldSpecified;
            }
            set
            {
                this.prismFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double prismAxis
        {
            get
            {
                return this.prismAxisField;
            }
            set
            {
                this.prismAxisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prismAxisSpecified
        {
            get
            {
                return this.prismAxisFieldSpecified;
            }
            set
            {
                this.prismAxisFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double sphere
        {
            get
            {
                return this.sphereField;
            }
            set
            {
                this.sphereField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sphereSpecified
        {
            get
            {
                return this.sphereFieldSpecified;
            }
            set
            {
                this.sphereFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(codifiableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(descriptableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(groupDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(shopDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(refractometrySideDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(refractometryDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(visusDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(optometryParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(opticalCorrectionsDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(optometryDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(personDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(legalPersonDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(naturalPersonDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(opticalParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(opticalCorrectionDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(lensCorrectionDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(eyeParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(lensParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(keratometrySideDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(keratometryDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(forieDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(keratometrySideParametersDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public abstract partial class validableDTO : deletableDTO
    {
        
        private bool validField;
        
        private bool validFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool valid
        {
            get
            {
                return this.validField;
            }
            set
            {
                this.validField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validSpecified
        {
            get
            {
                return this.validFieldSpecified;
            }
            set
            {
                this.validFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(validableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(codifiableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(descriptableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(groupDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(shopDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(refractometrySideDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(refractometryDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(visusDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(optometryParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(opticalCorrectionsDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(optometryDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(personDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(legalPersonDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(naturalPersonDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(opticalParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(opticalCorrectionDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(lensCorrectionDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(eyeParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(lensParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(keratometrySideDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(keratometryDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(forieDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(keratometrySideParametersDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public abstract partial class deletableDTO : modifiableDTO
    {
        
        private bool deletedField;
        
        private bool deletedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool deleted
        {
            get
            {
                return this.deletedField;
            }
            set
            {
                this.deletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deletedSpecified
        {
            get
            {
                return this.deletedFieldSpecified;
            }
            set
            {
                this.deletedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(deletableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(validableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(codifiableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(descriptableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(groupDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(shopDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(refractometrySideDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(refractometryDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(visusDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(optometryParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(opticalCorrectionsDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(optometryDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(personDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(legalPersonDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(naturalPersonDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(opticalParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(opticalCorrectionDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(lensCorrectionDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(eyeParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(lensParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(keratometrySideDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(keratometryDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(forieDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(keratometrySideParametersDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public abstract partial class modifiableDTO : createdDTO
    {
        
        private System.DateTime modifiedField;
        
        private bool modifiedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime modified
        {
            get
            {
                return this.modifiedField;
            }
            set
            {
                this.modifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modifiedSpecified
        {
            get
            {
                return this.modifiedFieldSpecified;
            }
            set
            {
                this.modifiedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(modifiableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(deletableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(validableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(codifiableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(descriptableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(groupDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(shopDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(refractometrySideDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(refractometryDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(visusDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(optometryParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(opticalCorrectionsDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(optometryDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(personDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(legalPersonDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(naturalPersonDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(opticalParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(opticalCorrectionDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(lensCorrectionDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(eyeParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(lensParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(keratometrySideDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(keratometryDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(forieDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(keratometrySideParametersDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public abstract partial class createdDTO : identifiableDTO
    {
        
        private System.DateTime creationField;
        
        private bool creationFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime creation
        {
            get
            {
                return this.creationField;
            }
            set
            {
                this.creationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creationSpecified
        {
            get
            {
                return this.creationFieldSpecified;
            }
            set
            {
                this.creationFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(createdDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(modifiableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(deletableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(validableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(codifiableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(descriptableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(groupDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(shopDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(refractometrySideDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(refractometryDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(visusDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(optometryParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(opticalCorrectionsDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(optometryDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(personDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(legalPersonDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(naturalPersonDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(opticalParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(opticalCorrectionDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(lensCorrectionDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(eyeParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(lensParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(keratometrySideDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(keratometryDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(forieDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(keratometrySideParametersDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public abstract partial class identifiableDTO : jsonbPolimorphic
    {
        
        private string idField;
        
        private long versionField;
        
        private bool versionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool versionSpecified
        {
            get
            {
                return this.versionFieldSpecified;
            }
            set
            {
                this.versionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(findCriteriaDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(relationalCriteriaDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(rangeCriteriaDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(simpleCriteriaDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(findResultDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(identifiableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(createdDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(modifiableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(deletableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(validableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(codifiableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(descriptableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(groupDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(shopDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(refractometrySideDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(refractometryDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(visusDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(optometryParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(opticalCorrectionsDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(optometryDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(personDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(legalPersonDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(naturalPersonDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(opticalParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(opticalCorrectionDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(lensCorrectionDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(eyeParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(lensParametersDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(keratometrySideDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(keratometryDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(forieDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(keratometrySideParametersDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public abstract partial class jsonbPolimorphic
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(relationalCriteriaDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(rangeCriteriaDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(simpleCriteriaDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public abstract partial class findCriteriaDTO : jsonbPolimorphic
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class relationalCriteriaDTO : findCriteriaDTO
    {
        
        private findCriteriaDTO relatedField;
        
        private relationalCriteriaDTOEntry[] relationsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public findCriteriaDTO related
        {
            get
            {
                return this.relatedField;
            }
            set
            {
                this.relatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public relationalCriteriaDTOEntry[] relations
        {
            get
            {
                return this.relationsField;
            }
            set
            {
                this.relationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class relationalCriteriaDTOEntry
    {
        
        private string keyField;
        
        private findCriteriaDTO valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public findCriteriaDTO value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class rangeCriteriaDTO : findCriteriaDTO
    {
        
        private identifiableDTO fromField;
        
        private identifiableDTO toField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public identifiableDTO from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public identifiableDTO to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class simpleCriteriaDTO : findCriteriaDTO
    {
        
        private identifiableDTO criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public identifiableDTO criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class findResultDTO : jsonbPolimorphic
    {
        
        private long countField;
        
        private bool countFieldSpecified;
        
        private identifiableDTO[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified
        {
            get
            {
                return this.countFieldSpecified;
            }
            set
            {
                this.countFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("results", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public identifiableDTO[] results
        {
            get
            {
                return this.resultsField;
            }
            set
            {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(descriptableDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(groupDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(shopDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public abstract partial class codifiableDTO : validableDTO
    {
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(groupDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(shopDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public abstract partial class descriptableDTO : codifiableDTO
    {
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(shopDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class groupDTO : descriptableDTO
    {
        
        private groupDTO parentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public groupDTO parent
        {
            get
            {
                return this.parentField;
            }
            set
            {
                this.parentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class shopDTO : groupDTO
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class refractometrySideDTO : validableDTO
    {
        
        private double axisField;
        
        private bool axisFieldSpecified;
        
        private double cylinderField;
        
        private bool cylinderFieldSpecified;
        
        private double sphereField;
        
        private bool sphereFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double axis
        {
            get
            {
                return this.axisField;
            }
            set
            {
                this.axisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool axisSpecified
        {
            get
            {
                return this.axisFieldSpecified;
            }
            set
            {
                this.axisFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double cylinder
        {
            get
            {
                return this.cylinderField;
            }
            set
            {
                this.cylinderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cylinderSpecified
        {
            get
            {
                return this.cylinderFieldSpecified;
            }
            set
            {
                this.cylinderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double sphere
        {
            get
            {
                return this.sphereField;
            }
            set
            {
                this.sphereField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sphereSpecified
        {
            get
            {
                return this.sphereFieldSpecified;
            }
            set
            {
                this.sphereFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class refractometryDTO : validableDTO
    {
        
        private refractometrySideDTO leftField;
        
        private refractometrySideDTO rightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public refractometrySideDTO left
        {
            get
            {
                return this.leftField;
            }
            set
            {
                this.leftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public refractometrySideDTO right
        {
            get
            {
                return this.rightField;
            }
            set
            {
                this.rightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class visusDTO : validableDTO
    {
        
        private double binocularField;
        
        private bool binocularFieldSpecified;
        
        private double leftField;
        
        private bool leftFieldSpecified;
        
        private double rightField;
        
        private bool rightFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double binocular
        {
            get
            {
                return this.binocularField;
            }
            set
            {
                this.binocularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool binocularSpecified
        {
            get
            {
                return this.binocularFieldSpecified;
            }
            set
            {
                this.binocularFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double left
        {
            get
            {
                return this.leftField;
            }
            set
            {
                this.leftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool leftSpecified
        {
            get
            {
                return this.leftFieldSpecified;
            }
            set
            {
                this.leftFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double right
        {
            get
            {
                return this.rightField;
            }
            set
            {
                this.rightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rightSpecified
        {
            get
            {
                return this.rightFieldSpecified;
            }
            set
            {
                this.rightFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class optometryParametersDTO : validableDTO
    {
        
        private double interpupillaryDistanceField;
        
        private bool interpupillaryDistanceFieldSpecified;
        
        private eyeParametersDTO leftField;
        
        private eyeParametersDTO rightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double interpupillaryDistance
        {
            get
            {
                return this.interpupillaryDistanceField;
            }
            set
            {
                this.interpupillaryDistanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool interpupillaryDistanceSpecified
        {
            get
            {
                return this.interpupillaryDistanceFieldSpecified;
            }
            set
            {
                this.interpupillaryDistanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public eyeParametersDTO left
        {
            get
            {
                return this.leftField;
            }
            set
            {
                this.leftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public eyeParametersDTO right
        {
            get
            {
                return this.rightField;
            }
            set
            {
                this.rightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(lensParametersDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class eyeParametersDTO : opticalParametersDTO
    {
        
        private double semiquotaField;
        
        private bool semiquotaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double semiquota
        {
            get
            {
                return this.semiquotaField;
            }
            set
            {
                this.semiquotaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool semiquotaSpecified
        {
            get
            {
                return this.semiquotaFieldSpecified;
            }
            set
            {
                this.semiquotaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class lensParametersDTO : eyeParametersDTO
    {
        
        private double additionField;
        
        private bool additionFieldSpecified;
        
        private double baseField;
        
        private bool baseFieldSpecified;
        
        private double decenteringField;
        
        private bool decenteringFieldSpecified;
        
        private double horizontalDiameterField;
        
        private bool horizontalDiameterFieldSpecified;
        
        private double verticalDiameterField;
        
        private bool verticalDiameterFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double addition
        {
            get
            {
                return this.additionField;
            }
            set
            {
                this.additionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool additionSpecified
        {
            get
            {
                return this.additionFieldSpecified;
            }
            set
            {
                this.additionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double @base
        {
            get
            {
                return this.baseField;
            }
            set
            {
                this.baseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool baseSpecified
        {
            get
            {
                return this.baseFieldSpecified;
            }
            set
            {
                this.baseFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double decentering
        {
            get
            {
                return this.decenteringField;
            }
            set
            {
                this.decenteringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool decenteringSpecified
        {
            get
            {
                return this.decenteringFieldSpecified;
            }
            set
            {
                this.decenteringFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double horizontalDiameter
        {
            get
            {
                return this.horizontalDiameterField;
            }
            set
            {
                this.horizontalDiameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool horizontalDiameterSpecified
        {
            get
            {
                return this.horizontalDiameterFieldSpecified;
            }
            set
            {
                this.horizontalDiameterFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double verticalDiameter
        {
            get
            {
                return this.verticalDiameterField;
            }
            set
            {
                this.verticalDiameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool verticalDiameterSpecified
        {
            get
            {
                return this.verticalDiameterFieldSpecified;
            }
            set
            {
                this.verticalDiameterFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(legalPersonDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(naturalPersonDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class personDTO : validableDTO
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class legalPersonDTO : personDTO
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class naturalPersonDTO : personDTO
    {
        
        private System.DateTime birthField;
        
        private bool birthFieldSpecified;
        
        private string firstnameField;
        
        private gender genderField;
        
        private bool genderFieldSpecified;
        
        private string surnameField;
        
        private string taxCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime birth
        {
            get
            {
                return this.birthField;
            }
            set
            {
                this.birthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthSpecified
        {
            get
            {
                return this.birthFieldSpecified;
            }
            set
            {
                this.birthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string firstname
        {
            get
            {
                return this.firstnameField;
            }
            set
            {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public gender gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool genderSpecified
        {
            get
            {
                return this.genderFieldSpecified;
            }
            set
            {
                this.genderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string surname
        {
            get
            {
                return this.surnameField;
            }
            set
            {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string taxCode
        {
            get
            {
                return this.taxCodeField;
            }
            set
            {
                this.taxCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public enum gender
    {
        
        /// <remarks/>
        MALE,
        
        /// <remarks/>
        FEMALE,
        
        /// <remarks/>
        UNKNOWN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class keratometrySideDTO : validableDTO
    {
        
        private double astigmatismField;
        
        private bool astigmatismFieldSpecified;
        
        private keratometrySideParametersDTO firstField;
        
        private keratometrySideParametersDTO secondField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double astigmatism
        {
            get
            {
                return this.astigmatismField;
            }
            set
            {
                this.astigmatismField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool astigmatismSpecified
        {
            get
            {
                return this.astigmatismFieldSpecified;
            }
            set
            {
                this.astigmatismFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public keratometrySideParametersDTO first
        {
            get
            {
                return this.firstField;
            }
            set
            {
                this.firstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public keratometrySideParametersDTO second
        {
            get
            {
                return this.secondField;
            }
            set
            {
                this.secondField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class keratometrySideParametersDTO : validableDTO
    {
        
        private double dioptersField;
        
        private bool dioptersFieldSpecified;
        
        private double meridianField;
        
        private bool meridianFieldSpecified;
        
        private double radiusField;
        
        private bool radiusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double diopters
        {
            get
            {
                return this.dioptersField;
            }
            set
            {
                this.dioptersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dioptersSpecified
        {
            get
            {
                return this.dioptersFieldSpecified;
            }
            set
            {
                this.dioptersFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double meridian
        {
            get
            {
                return this.meridianField;
            }
            set
            {
                this.meridianField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool meridianSpecified
        {
            get
            {
                return this.meridianFieldSpecified;
            }
            set
            {
                this.meridianFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double radius
        {
            get
            {
                return this.radiusField;
            }
            set
            {
                this.radiusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool radiusSpecified
        {
            get
            {
                return this.radiusFieldSpecified;
            }
            set
            {
                this.radiusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class keratometryDTO : validableDTO
    {
        
        private keratometrySideDTO leftField;
        
        private string noteField;
        
        private keratometrySideDTO rightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public keratometrySideDTO left
        {
            get
            {
                return this.leftField;
            }
            set
            {
                this.leftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public keratometrySideDTO right
        {
            get
            {
                return this.rightField;
            }
            set
            {
                this.rightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class forieDTO : validableDTO
    {
        
        private double correctedField;
        
        private bool correctedFieldSpecified;
        
        private double plainField;
        
        private bool plainFieldSpecified;
        
        private forieType typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double corrected
        {
            get
            {
                return this.correctedField;
            }
            set
            {
                this.correctedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool correctedSpecified
        {
            get
            {
                return this.correctedFieldSpecified;
            }
            set
            {
                this.correctedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double plain
        {
            get
            {
                return this.plainField;
            }
            set
            {
                this.plainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool plainSpecified
        {
            get
            {
                return this.plainFieldSpecified;
            }
            set
            {
                this.plainFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public forieType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public enum forieType
    {
        
        /// <remarks/>
        LEFT,
        
        /// <remarks/>
        RIGHT,
        
        /// <remarks/>
        UNKNOWN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public partial class lensCorrectionDTO : opticalCorrectionDTO
    {
        
        private lensType lensTypeField;
        
        private bool lensTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public lensType lensType
        {
            get
            {
                return this.lensTypeField;
            }
            set
            {
                this.lensTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lensTypeSpecified
        {
            get
            {
                return this.lensTypeFieldSpecified;
            }
            set
            {
                this.lensTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public enum lensType
    {
        
        /// <remarks/>
        MONOFOCAL,
        
        /// <remarks/>
        BIFOCAL,
        
        /// <remarks/>
        PROGRESSIVE,
        
        /// <remarks/>
        OFFICE,
        
        /// <remarks/>
        ANTIFATIGUE,
        
        /// <remarks/>
        OTHER,
        
        /// <remarks/>
        UNKNOWN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.service.optoplus.visiontech.org/")]
    public enum systemType
    {
        
        /// <remarks/>
        TABO,
        
        /// <remarks/>
        INTERNATIONAL,
        
        /// <remarks/>
        UNKNOWN,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://soap.service.optoplus.visiontech.org/", IsWrapped=true)]
    public partial class delete
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.service.optoplus.visiontech.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Org.Visiontech.Optometry.optometryDTO[] arg0;
        
        public delete()
        {
        }
        
        public delete(Org.Visiontech.Optometry.optometryDTO[] arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://soap.service.optoplus.visiontech.org/", IsWrapped=true)]
    public partial class deleteResponse
    {
        
        public deleteResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="edit", WrapperNamespace="http://soap.service.optoplus.visiontech.org/", IsWrapped=true)]
    public partial class edit
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.service.optoplus.visiontech.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Org.Visiontech.Optometry.optometryDTO[] arg0;
        
        public edit()
        {
        }
        
        public edit(Org.Visiontech.Optometry.optometryDTO[] arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editResponse", WrapperNamespace="http://soap.service.optoplus.visiontech.org/", IsWrapped=true)]
    public partial class editResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.service.optoplus.visiontech.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Org.Visiontech.Optometry.optometryDTO[] @return;
        
        public editResponse()
        {
        }
        
        public editResponse(Org.Visiontech.Optometry.optometryDTO[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="find", WrapperNamespace="http://soap.service.optoplus.visiontech.org/", IsWrapped=true)]
    public partial class find
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.service.optoplus.visiontech.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Org.Visiontech.Optometry.findCriteriaDTO[] arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.service.optoplus.visiontech.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.service.optoplus.visiontech.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        public find()
        {
        }
        
        public find(Org.Visiontech.Optometry.findCriteriaDTO[] arg0, int arg1, int arg2)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findResponse", WrapperNamespace="http://soap.service.optoplus.visiontech.org/", IsWrapped=true)]
    public partial class findResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.service.optoplus.visiontech.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Org.Visiontech.Optometry.findResultDTO @return;
        
        public findResponse()
        {
        }
        
        public findResponse(Org.Visiontech.Optometry.findResultDTO @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="create", WrapperNamespace="http://soap.service.optoplus.visiontech.org/", IsWrapped=true)]
    public partial class create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.service.optoplus.visiontech.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Org.Visiontech.Optometry.optometryDTO[] arg0;
        
        public create()
        {
        }
        
        public create(Org.Visiontech.Optometry.optometryDTO[] arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createResponse", WrapperNamespace="http://soap.service.optoplus.visiontech.org/", IsWrapped=true)]
    public partial class createResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.service.optoplus.visiontech.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Org.Visiontech.Optometry.optometryDTO[] @return;
        
        public createResponse()
        {
        }
        
        public createResponse(Org.Visiontech.Optometry.optometryDTO[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OptometrySoapChannel : Org.Visiontech.Optometry.OptometrySoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OptometrySoapClient : System.ServiceModel.ClientBase<Org.Visiontech.Optometry.OptometrySoap>, Org.Visiontech.Optometry.OptometrySoap
    {
        
        public OptometrySoapClient()
        {
        }
        
        public OptometrySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public OptometrySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public OptometrySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public OptometrySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Org.Visiontech.Optometry.deleteResponse Org.Visiontech.Optometry.OptometrySoap.delete(Org.Visiontech.Optometry.delete request)
        {
            return base.Channel.delete(request);
        }
        
        public void delete(Org.Visiontech.Optometry.optometryDTO[] arg0)
        {
            Org.Visiontech.Optometry.delete inValue = new Org.Visiontech.Optometry.delete();
            inValue.arg0 = arg0;
            Org.Visiontech.Optometry.deleteResponse retVal = ((Org.Visiontech.Optometry.OptometrySoap)(this)).delete(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Org.Visiontech.Optometry.editResponse Org.Visiontech.Optometry.OptometrySoap.edit(Org.Visiontech.Optometry.edit request)
        {
            return base.Channel.edit(request);
        }
        
        public Org.Visiontech.Optometry.optometryDTO[] edit(Org.Visiontech.Optometry.optometryDTO[] arg0)
        {
            Org.Visiontech.Optometry.edit inValue = new Org.Visiontech.Optometry.edit();
            inValue.arg0 = arg0;
            Org.Visiontech.Optometry.editResponse retVal = ((Org.Visiontech.Optometry.OptometrySoap)(this)).edit(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Org.Visiontech.Optometry.findResponse Org.Visiontech.Optometry.OptometrySoap.find(Org.Visiontech.Optometry.find request)
        {
            return base.Channel.find(request);
        }
        
        public Org.Visiontech.Optometry.findResultDTO find(Org.Visiontech.Optometry.findCriteriaDTO[] arg0, int arg1, int arg2)
        {
            Org.Visiontech.Optometry.find inValue = new Org.Visiontech.Optometry.find();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            Org.Visiontech.Optometry.findResponse retVal = ((Org.Visiontech.Optometry.OptometrySoap)(this)).find(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Org.Visiontech.Optometry.createResponse Org.Visiontech.Optometry.OptometrySoap.create(Org.Visiontech.Optometry.create request)
        {
            return base.Channel.create(request);
        }
        
        public Org.Visiontech.Optometry.optometryDTO[] create(Org.Visiontech.Optometry.optometryDTO[] arg0)
        {
            Org.Visiontech.Optometry.create inValue = new Org.Visiontech.Optometry.create();
            inValue.arg0 = arg0;
            Org.Visiontech.Optometry.createResponse retVal = ((Org.Visiontech.Optometry.OptometrySoap)(this)).create(inValue);
            return retVal.@return;
        }
    }
}
